version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    container_name: NestNextLectureWooram
    environment:
      POSTGRES_USER: nestWooram
      POSTGRES_PASSWORD: nestWooram
      POSTGRES_DB: nestWooram
    restart: always
    networks:
      - lesson
networks:
  lesson: